packages:
  - "apps/*"
  - "packages/*"
  - "workers/*"

autoInstallPeers: false
injectWorkspacePackages: true
linkWorkspacePackages: true
nodeLinker: hoisted
packageImportMethod: copy
strictPeerDependencies: true
