{{- range $name, $_ := .Values.components }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eventrail.fullname" $ }}-{{ $name }}
  labels:
    {{- include "eventrail.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
