// Generated from openapi/eventrail.v1.yaml. Validate through `pnpm openapi:types`.
export type EventRailApiPath =
  | "/v1/health"
  | "/v1/markets"
  | "/v1/data/series"
  | "/v1/data/markets"
  | "/v1/data/markets/{marketId}"
  | "/v1/data/markets/{marketId}/resolution"
  | "/v1/data/markets/{marketId}/book"
  | "/v1/data/markets/{marketId}/trades"
  | "/v1/data/markets/{marketId}/candles"
  | "/v1/data/markets/{marketId}/quote"
  | "/v1/trading/quotes"
  | "/v1/trading/plans"
  | "/v1/trading/submissions"
  | "/v1/funding/routes"
  | "/v1/redemptions/plans"
  | "/v1/builders/approval-plans"
  | "/v1/data/accounts/{account}/positions"
  | "/v1/data/accounts/{account}/activity"
  | "/v1/data/accounts/{account}/claims"
  | "/v1/data/accounts/{account}/balances/{marketId}"
  | "/v1/events"
  | "/v1/integrators"
  | "/v1/integrators/{integratorId}/keys"
  | "/v1/integrators/{integratorId}/keys/{keyId}"
  | "/v1/integrators/{integratorId}/config"
  | "/v1/integrators/{integratorId}/analytics/events"
  | "/v1/integrators/{integratorId}/analytics/summary"
  | "/v1/integrators/{integratorId}/analytics/retention"
  | "/v1/integrators/{integratorId}/webhooks"
  | "/v1/integrators/{integratorId}/webhooks/{endpointId}/rotate"
  | "/v1/integrators/{integratorId}/webhook-deliveries"
  | "/v1/integrators/{integratorId}/webhook-deliveries/{deliveryId}/replay";
export type EventRailApiMethod = "GET" | "POST" | "PUT" | "DELETE";
